version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
          - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: debug_apks

      - store_test_results:
          path: app/build/test-results/

workflows:
  build_and_test:
    jobs:
      - build
